modules:
  motd:
    enabled: true
    messages:
      motd: "&aWelcome to the server!"

  oreWatcher:
    enabled: false

    # The amount of ore mined per minute to trigger an alert
    alertThreshold: 30
    # Whether to cancel the mining event if the alert threshold is exceeded
    cancelMinedOverThreshold: false

    # Config for the alert messages
    adminAlertEnabled: true
    playerAlertEnabled: false

    messages:
      # Available message placeholders:
      #   %player% - The name of the player
      #   %blockname% - The name of the block being mined
      #   %oreperminute% - The amount of ore mined per minute

      # The message to send to any admins with the permission taterutils.module.orewatcher.admin when the alert threshold is exceeded
      adminAlertMessage: "&c%playername% &7is mining &c %blockname% ยง7at a rate of &c %oreperminute% &7per minute!"

      # The message to send to the player when the alert threshold is exceeded
      playerAlertMessage: "&cYou are mining ore a bit too fast there, buddy!"

  ping:
    enabled: true
    messages:
      # Available message placeholders:
      #   %player% - The name of the player
      #   %ping% - The player's ping
      pingSelf: "&aYour ping is &e%ping%ms&a!"
      pingOther: "&a%player%'s ping is &e%ping%ms&a!"
      pingOtherDenied: "&cYou do not have permission to view other players' ping!"
      specifyPlayer: "&cPlease specify a player!"
      playerNotFound: "&cPlayer not found!"

  slashLobby:
    enabled: true

    # The name of the lobby/hub server to send players to
    lobbyNames: [ "lobby", "hub" ]

    messages:
      lobby:
        # Available message placeholders:
        #   %lobby% - The name of the lobby
        connectedToLobby: "&aConnected to &e%lobby%&a!"

  spawn:
    enabled: true
    messages:
      spawn:
        spawnNotSet: "&cSpawn has not been set!"
        teleportedToSpawn: "&aTeleporting to spawn!"
        setSpawn:
          success: "&aSet spawn location!"
        deleteSpawn:
          success: "&aDeleted spawn location!"
