modules:
  ping:
    enabled: true
    messages:
      # Available message placeholders:
      #   %player% - The name of the player
      #   %ping% - The player's ping
      pingSelf: "&aYour ping is &e%ping%ms&a!"
      pingOther: "&a%player%'s ping is &e%ping%ms&a!"
      pingOtherDenied: "&cYou do not have permission to view other players' ping!"
      specifyPlayer: "&cPlease specify a player!"
      playerNotFound: "&cPlayer not found!"

  slashLobby:
    enabled: true

    # The name of the lobby/hub server to send players to
    lobbyNames: [ "lobby", "hub" ]

    messages:
      lobby:
        # Available message placeholders:
        #   %lobby% - The name of the lobby
        connectedToLobby: "&aConnected to &e%lobby%&a!"

  spawn:
    enabled: true
    messages:
      spawn:
        spawnNotSet: "&cSpawn has not been set!"
        teleportedToSpawn: "&aTeleporting to spawn!"
        setSpawn:
          success: "&aSet spawn location!"
        deleteSpawn:
          success: "&aDeleted spawn location!"
