modules:
  spawn:
    enabled: true
    messages:
      spawn:
        spawnNotSet: "&cSpawn has not been set!"
        teleportedToSpawn: "&aTeleporting to spawn!"
        setSpawn:
          success: "&aSet spawn location!"
        deleteSpawn:
          success: "&aDeleted spawn location!"
