name: '${project_name}'
version: '${version}'
author: '${authors}'
description: '${project_description}'
main: '${group_id}.${project_id}.bukkit.BukkitPlugin'
depends: [TaterLib]
softdepends: [LuckPerms]
folia-supported: true
commands:
  home:
    description: Teleport to a home
    usage: /home [name | del | set | list] [name]
    permission: taterlib.command.home
  sethome:
    description: Set a home
    usage: /sethome [name]
    permission: taterlib.command.sethome
  delhome:
    description: Delete a home
    usage: /delhome [name]
    permission: taterlib.command.delhome
  warp:
    description: Warp to a location
    usage: /warp [name | list]
    permission: taterlib.command.warp
  setwarp:
    description: Set or delete a warp locatioon
    usage: /setwarp <name>
    permission: taterlib.command.setwarp
  delwarp:
    description: Delete a warp location
    usage: /delwarp <name>
    permission: taterlib.command.delwarp
