name: '${project_name}'
version: '${version}'
author: '${authors}'
description: '${project_description}'
main: '${group_id}.${project_id}.bukkit.BukkitPlugin'
depends: [TaterLib]
softdepends: [LuckPerms]
folia-supported: true
commands:
  home:
    description: Teleport to your home
    usage: /home [name|set|delete]
    permission: taterlib.command.home
  setwarp:
    description: Set or delete a warp locatioon
    usage: /setwarp [set|delete] [name]
    permission: taterlib.command.setwarp
  warp:
    description: Allows players to Send a teleport request to another player!
    usage: /warp [name]
    permission: taterlib.command.warp