name: '${project_name}'
version: '${version}'
author: '${authors}'
description: '${project_description}'
website: '${homepage_url}'
main: '${group_id}.${project_id}.platforms.BukkitPlugin'
depends: [ TaterLib ]
softdepends: [ LuckPerms ]
folia-supported: true
commands:
  alert:
    description: Send an alert to all players
    usage: /alert <message>
    permission: taterlib.command.alert
  home:
    description: Teleport to a home
    usage: /home [name | del | set | list] [name]
    permission: taterlib.command.home
  sethome:
    description: Set a home
    usage: /sethome [name]
    permission: taterlib.command.sethome
    aliases: [ addhome, createhome ]
  delhome:
    description: Delete a home
    usage: /delhome [name]
    permission: taterlib.command.delhome
    aliases: [ deletehome, rmhome, removehome ]
  mclogs:
    description: Upload logs to mclo.gs
    usage: /mclogs ...
    permission: taterlib.command.mclogs
  ping:
    description: Gets the ping of a player
    usage: /ping [player]
    permission: taterlib.command.ping
  spawn:
    description: Teleport to spawn
    usage: /spawn
    permission: taterlib.command.spawn
  setspawn:
    description: Set the spawn
    usage: /setspawn
    permission: taterlib.command.setspawn
    aliases: [ addspawn, createspawn ]
  delspawn:
    description: Delete the spawn
    usage: /delspawn
    permission: taterlib.command.delspawn
    aliases: [ deletespawn, rmspawn, removespawn ]
  tpa:
    description: Request to teleport to a player
    usage: /tpa <player>
    permission: taterlib.command.tpa
  tphere:
    description: Request to teleport a player to you
    usage: /tphere <player>
    permission: taterlib.command.tphere
    aliases: [ tpahere ]
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept
    permission: taterlib.command.tpaccept
  tpdeny:
    description: Deny a teleport request
    usage: /tpdeny
    permission: taterlib.command.tpdeny
  warp:
    description: Warp to a location
    usage: /warp [name | list]
    permission: taterlib.command.warp
    aliases: [ warps ]
  setwarp:
    description: Set or delete a warp locatioon
    usage: /setwarp <name>
    permission: taterlib.command.setwarp
    aliases: [ addwarp, createwarp ]
  delwarp:
    description: Delete a warp location
    usage: /delwarp <name>
    permission: taterlib.command.delwarp
    aliases: [ deletewarp, rmwarp, removewarp ]
